### ISSUE TITLE
there's no jar file

### ISSUE THREAD

**Issue by unmellow** [hanss314/GOLAD#10]
i downloaded the zip and extracted it and there was no jar file

**Comment by denezrg** [comment]
who directed u to this email, this aint that dude

**Comment by ramzialhaddad** [comment]
Are you sure you are downloading it from the releases tab?

**Comment by unmellow** [comment]
i'll try it again later but i'm certain i did

**Comment by unmellow** [comment]
i'll try it again later but i'm certain i did

**Comment by unmellow** [comment]
i'm not sure what you mean i clicked the download link in the read me i don't see a tab that say's release

**Comment by ramzialhaddad** [comment]
https://github.com/hanss314/GOLAD/archive/v1.6.1.zip here is the link

**Comment by unmellow** [comment]
thanks and you should add that link to the readme.MD (in case someone else makes the same mistake as me)

**Comment by ramzialhaddad** [comment]
Its from the releases lol

**Comment by unmellow** [comment]
I know but I couldn't find the release tab lol I probably won't be the last 

edit: forgot to close
