### ISSUE TITLE
Program doesn't open

### ISSUE THREAD

**Issue by qixils** [hanss314/GOLAD#3]
[Reported by RedsToad#4613 on Discord]
Screenshot of error given:
![image](https://cdn.discordapp.com/attachments/188369954926493697/280380307557842944/Screenshot_27.png)

**Comment by hanss314** [comment]
I can't seem to replicate the results on my computer.

**Comment by qixils** [comment]
Also cannot reproduce on Ubuntu 16.04, with openjdk version of java 1.8.0_121

**Comment by qixils** [comment]
Reporter was on an outdated Java, updating fixed it.
