### ISSUE TITLE
Odd text clipping in tutorial

### ISSUE THREAD

**Issue by qixils** [hanss314/GOLAD#4]
**Bug:** Some text clips outside of the white margins (to the left & right) in the tutorial.
**Screenshot:**
![image](https://cloud.githubusercontent.com/assets/13265322/22864622/f2ef5986-f122-11e6-8486-f15526e85f31.png)
**OS:** Ubuntu 16.04
**Java:** `openjdk version "1.8.0_121"`

**Comment by hanss314** [comment]
Yeah, that's an issue on ubuntu, but it works fine on windows

**Comment by hanss314** [comment]
I can make the font smaller but it looks weird on windows

**Comment by hanss314** [comment]
Does this work? https://github.com/hanss314/GOLAD/tree/FontTest

**Comment by qixils** [comment]
Latest commit in FontTest works fine.
If it works fine on Windows, you may want to consider changing font size depending on the OS. You can grab the OS name with java using `System.getProperty("os.name")`

**Comment by hanss314** [comment]
That's exactly what I did
